[package]
name = "wasm-playground"
version = "0.1.0"
repository = "https://github.com/BaseW/wasm-playground"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.120"
wasm-bindgen = "0.2"
